### ISSUE TITLE
Duplicate lines at file creation

### ISSUE THREAD

**Issue by NannoSilver** [kendimaru/textfile#1]
This library is very useful and I am using it to handle TXT files.

Using it, I found what seems to be a bug for the `append` function.
If the file to append the text is not present in the disk, then the file is created, however, the text is **written twice**. 
That problem happens only at the file creation. If the file is already present in the disk, the problem does not occur.

This is the code:
```
def append_to_file(file_and_path, message_to_append):
    try:
        textfile.append(file_and_path, message_to_append)
        logger.debug(f'TEXTFILE Library: APPEND to file [{file_and_path}] the message: [{message_to_append}]')
    except:
        logger.critical(f'TEXTFILE Library: Failed to write to file [{file_and_path}] the message: [{message_to_append}]')


append_to_file ('log/log.txt', '\nThis is only a test')
```

If the file log.txt is present in the disk, then everything goes well and the following line is append:
`This is only a test`

However, if the log.txt file is not present in the disk, then it is created with this content:
```

This is only a test
This is only a test
```

The text `This is only a test` is written twice!

Hope that can be fixed.

Thank you for making and maintain this useful library!

**Comment by NannoSilver** [comment]
Thank you for fixing!

**Comment by kendimaru** [comment]
Thank you, too, @sukhoi47.
Your very detailed report, it was very helpful for me!

I apologize for delayed the response to you, because this is my first time to communicate on GitHub.
