### ISSUE TITLE
Please show your license file at this repository

### ISSUE THREAD

**Issue by fu7mu4** [kendimaru/textfile#3]
I could not find the license file of this repository.
But I found MIT License at [the other place.](https://pypi.org/project/textfile/) 
Please add LICENSE file for MIT Licese

![image](https://github.com/user-attachments/assets/22560013-f03e-4eff-b0d9-587e3f3eea25)

**Comment by kendimaru** [comment]
I've recognized this issue. My intention is that this project is under the MIT License.
I will address this issue in a few days.
Thank you for posting.
